### ISSUE TITLE
Shipping the .idea files makes things very very awkward

### ISSUE THREAD

**Issue by alexpott** [php-tuf/composer-stager#57] opened 2023-01-10 10:21 UTC
If I open this repository in PHPStorm immediately after cloning I don't see any folders - i.e. src/ which makes the project unusable.

<img width="641" alt="CleanShot 2023-01-10 at 10 20 14@2x" src="https://user-images.githubusercontent.com/769634/211525019-8c34c6ab-1df1-4d2b-a2d9-d5f095b53cab.png">

**Comment by alexpott** [comment] 2023-01-10 10:25
In order to get the folders listed I need to:
1. Close the project in PHPStorm
2. Delete .idea from the project
3. Re-open the project

At this point I can then checkout .idea to restore what the project ships with and re-open the project and everything works as expected. But this is super super awkward.

**Comment by TravisCarden** [comment] 2023-01-10 16:14
Hmm. I'm not sure I've had that experience. I find it valuable to include the `.idea` directory for the same reasons as including any other dev tooling: convenience and consistency, etc.

Did this happen for you just once when you first set up the project? Or does it happen every time you open it up? Can you provide steps to reproduce?

**Comment by quietone1** [comment] 2023-01-10 22:42
I followed the same steps to reproduce and have the same problem. Closing and opening the project did not help.

```

1. git clone https://github.com/php-tuf/composer-stager.git
2. open project in PHPStorm and see no source files, same result as alexpott.
3. close project
4. open project
5. Still no source files
6. close project
7. rm -rf .idea
8. open project - the files appear

```

**Comment by TravisCarden** [comment] 2023-01-11 21:08
Okay, I see what the problem was. The `.idea/composer-stager.iml` file needed to be committed and wasn't. I've corrected it in `develop`. Please confirm.

**Closed** 2023-01-17 16:29 UTC
